FILE_INICIALITZADOR = 0-Inicialitzador
MK_INICIALITZADOR = $(FILE_INICIALITZADOR)/GNU.mk

# General.
INICIALITZADOR_C_	=		\
	$(INICIALIRZADOR_C_V00)		\

INICIALITZADOR_H_	=		\
	$(INICIALIRZADOR_H_V00)		\

INICIALITZADOR_O_	=		\
	$(INICIALIRZADOR_O_V00)		\
	$(INICIALITZADOR_ALLIBERAR_O_)	\

# v00
INICIALIRZADOR_C_V00 = $(FILE_INICIALITZADOR)/v00.c
INICIALIRZADOR_H_V00 = $(FILE_INICIALITZADOR)/v00.h
INICIALIRZADOR_O_V00 = $(OBJDIR)/inicialitzador-v00.o

# Alliberar memòria.
INICIALITZADOR_ALLIBERAR_C_ = $(FILE_INICIALITZADOR)/alliberar_memòria.c
INICIALITZADOR_ALLIBERAR_H_ = $(FILE_INICIALITZADOR)/alliberar_memòria.h
INICIALITZADOR_ALLIBERAR_O_ = $(OBJDIR)/inicialitzador_alliberar_memòria.o
