FILE_SINTACTIC = 4-Sintàctic

SINTACTIC_O_	=				\
	$(SINTACTIC_SHUNTING_YARD_ALGORITM_O_)	\

SINTACTIC_SHUNTING_YARD_ALGORITM_C_	=	$(FILE_SINTACTIC)/shunting-yard_algorithm.c
SINTACTIC_SHUNTING_YARD_ALGORITM_H_	=	$(FILE_SINTACTIC)/shunting-yard_algorithm.h
SINTACTIC_SHUNTING_YARD_ALGORITM_O_	=	$(OBJDIR)/shunting-yard_algorithm.o
