prova: prova.c v00-lèxic.h v00-lèxic.c maquina_estats.c maquina_estats.h ../../6-Depurador/menú.c ../../6-Depurador/depurador.c
	gcc prova.c v00-lèxic.c maquina_estats.c ../../6-Depurador/menú.c ../../6-Depurador/depurador.c -o prova -Wall -g
