prova: prova.c v00-lèxic.h v00-lèxic.c maquina_estats.c maquina_estats.h ../Depurador/menú.c ../Depurador/depurador.c
	gcc prova.c v00-lèxic.c maquina_estats.c ../Depurador/menú.c ../Depurador/depurador.c -o prova -Wall -g
