FILE_EXECUTOR = 1-Executor
MK_EXECUTOR = $(FILE_EXECUTOR)/GNU.mk

EXECUTOR_H_ =				\
	$(EXECUTOR_DESCRIPTOR_H_)	\
	$(EXECUTOR_EXECUTOR_H_)		\

# Dependencies al tenir la llibreria.
EXECUTOR_DESCRIPTOR_H_	=		\
	$(FILE_EXECUTOR)/descriptor.h		\

EXECUTOR_EXECUTOR_H_	=		\
	$(FILE_EXECUTOR)/executor.h		\
	$(EXECUTOR_DESCRIPTOR_H_)	\

EXECUTOR_EXECUTOR_O_	=		\
	$(FILE_EXECUTOR)/executor.c		\
	$(EXECUTOR_EXECUTOR_H_)		\
